//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ninja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Catagory
    {
        public Catagory()
        {
            this.Gear = new HashSet<Gear>();
        }
    
        public int catagoryId { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Gear> Gear { get; set; }
    }
}
