//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ninja
{
    using System;
    using System.Collections.Generic;
    
    public partial class Gear
    {
        public Gear()
        {
            this.Ninja = new HashSet<Ninja>();
        }
    
        public int gearId { get; set; }
        public int gold { get; set; }
        public Nullable<int> strength { get; set; }
        public Nullable<int> intelligence { get; set; }
        public Nullable<int> agility { get; set; }
        public int FK_Catagory_catagoryId { get; set; }
    
        public virtual Catagory Catagory { get; set; }
        public virtual ICollection<Ninja> Ninja { get; set; }
    }
}
